# Generated by Django 5.0.4 on 2024-08-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_filmwork_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer')], verbose_name='role'),
        ),
    ]
